services:
  postgres:
    image: postgres:latest
    container_name: lumi-db
    restart: always
    environment:
      POSTGRES_USER: lumi_user
      POSTGRES_PASSWORD: lumi123
      POSTGRES_DB: lumi
    ports:
      - "5432:5432"

  api:
    build:
      dockerfile: Dockerfile
      context: ./lumi-api/
    container_name: lumi-api
    working_dir: /app
    restart: always
    volumes:
      - ./lumi-api:/app
      - node_modules:/app/node_modules
    ports:
      - "5000:5000"
    environment:
      NODE_ENV: development
    depends_on:
      - postgres

  frontend:
    build:
      dockerfile: Dockerfile
      context: ./lumi-frontend/
    container_name: lumi-frontend 
    working_dir: /app
    restart: always
    volumes:
      - ./lumi-frontend:/app
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: development

volumes:
  node_modules:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./lumi-api/node_modules